// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Object_Kinect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X    uint32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y    uint32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Dist uint32 `protobuf:"varint,4,opt,name=dist,proto3" json:"dist,omitempty"`
	Conf uint32 `protobuf:"varint,5,opt,name=conf,proto3" json:"conf,omitempty"`
}

func (x *Object_Kinect) Reset() {
	*x = Object_Kinect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object_Kinect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object_Kinect) ProtoMessage() {}

func (x *Object_Kinect) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object_Kinect.ProtoReflect.Descriptor instead.
func (*Object_Kinect) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Object_Kinect) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object_Kinect) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Object_Kinect) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Object_Kinect) GetDist() uint32 {
	if x != nil {
		return x.Dist
	}
	return 0
}

func (x *Object_Kinect) GetConf() uint32 {
	if x != nil {
		return x.Conf
	}
	return 0
}

type Object_Omni struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X    uint32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y    uint32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Dist uint32 `protobuf:"varint,4,opt,name=dist,proto3" json:"dist,omitempty"`
	Conf uint32 `protobuf:"varint,6,opt,name=conf,proto3" json:"conf,omitempty"`
}

func (x *Object_Omni) Reset() {
	*x = Object_Omni{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object_Omni) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object_Omni) ProtoMessage() {}

func (x *Object_Omni) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object_Omni.ProtoReflect.Descriptor instead.
func (*Object_Omni) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Object_Omni) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object_Omni) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Object_Omni) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Object_Omni) GetDist() uint32 {
	if x != nil {
		return x.Dist
	}
	return 0
}

func (x *Object_Omni) GetConf() uint32 {
	if x != nil {
		return x.Conf
	}
	return 0
}

type Request_Omni_Calib struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Check bool `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"` //bytes image = 2;
}

func (x *Request_Omni_Calib) Reset() {
	*x = Request_Omni_Calib{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_Omni_Calib) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Omni_Calib) ProtoMessage() {}

func (x *Request_Omni_Calib) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Omni_Calib.ProtoReflect.Descriptor instead.
func (*Request_Omni_Calib) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Request_Omni_Calib) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Check bool `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

type Request_BS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Check uint32 `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
}

func (x *Request_BS) Reset() {
	*x = Request_BS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_BS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_BS) ProtoMessage() {}

func (x *Request_BS) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_BS.ProtoReflect.Descriptor instead.
func (*Request_BS) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *Request_BS) GetCheck() uint32 {
	if x != nil {
		return x.Check
	}
	return 0
}

type Response_Omni struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Omni      []byte         `protobuf:"bytes,1,opt,name=omni,proto3" json:"omni,omitempty"`
	ImgToSend uint32         `protobuf:"varint,2,opt,name=img_to_send,json=imgToSend,proto3" json:"img_to_send,omitempty"`
	Objects   []*Object_Omni `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"` // 3 bytes 'classe' 'x' 'y'
}

func (x *Response_Omni) Reset() {
	*x = Response_Omni{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Omni) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Omni) ProtoMessage() {}

func (x *Response_Omni) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Omni.ProtoReflect.Descriptor instead.
func (*Response_Omni) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *Response_Omni) GetOmni() []byte {
	if x != nil {
		return x.Omni
	}
	return nil
}

func (x *Response_Omni) GetImgToSend() uint32 {
	if x != nil {
		return x.ImgToSend
	}
	return 0
}

func (x *Response_Omni) GetObjects() []*Object_Omni {
	if x != nil {
		return x.Objects
	}
	return nil
}

type Response_Kinect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kinect      []byte           `protobuf:"bytes,1,opt,name=kinect,proto3" json:"kinect,omitempty"`
	KinectDepth []byte           `protobuf:"bytes,2,opt,name=kinect_depth,json=kinectDepth,proto3" json:"kinect_depth,omitempty"`
	Objects     []*Object_Kinect `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"` // 4 bytes 'classe' 'x' 'y' 'dist'
}

func (x *Response_Kinect) Reset() {
	*x = Response_Kinect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Kinect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Kinect) ProtoMessage() {}

func (x *Response_Kinect) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Kinect.ProtoReflect.Descriptor instead.
func (*Response_Kinect) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *Response_Kinect) GetKinect() []byte {
	if x != nil {
		return x.Kinect
	}
	return nil
}

func (x *Response_Kinect) GetKinectDepth() []byte {
	if x != nil {
		return x.KinectDepth
	}
	return nil
}

func (x *Response_Kinect) GetObjects() []*Object_Kinect {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ResponseTo_BS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ResponseTo_BS) Reset() {
	*x = ResponseTo_BS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseTo_BS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTo_BS) ProtoMessage() {}

func (x *ResponseTo_BS) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTo_BS.ProtoReflect.Descriptor instead.
func (*ResponseTo_BS) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseTo_BS) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ResponseTo_BS) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x63, 0x0a, 0x0d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x4b, 0x69,
	0x6e, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x64, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x61, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x4f, 0x6d, 0x6e, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x64, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x2a, 0x0a, 0x12, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x4f, 0x6d, 0x6e, 0x69, 0x5f, 0x43, 0x61, 0x6c, 0x69,
	0x62, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x1f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x22, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x42, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x6e, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x4f, 0x6d, 0x6e, 0x69, 0x12, 0x12, 0x0a,
	0x04, 0x6f, 0x6d, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6f, 0x6d, 0x6e,
	0x69, 0x12, 0x1e, 0x0a, 0x0b, 0x69, 0x6d, 0x67, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x6d, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x6e,
	0x64, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x4f,
	0x6d, 0x6e, 0x69, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x79, 0x0a, 0x0f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x4b, 0x69, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6b, 0x69, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x6b, 0x69, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x69, 0x6e, 0x65, 0x63,
	0x74, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6b,
	0x69, 0x6e, 0x65, 0x63, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x2b, 0x0a, 0x07, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x4b, 0x69, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x07,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x42, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x47, 0x0a, 0x09, 0x59, 0x6f, 0x6c, 0x6f, 0x5f, 0x4f, 0x6d,
	0x6e, 0x69, 0x12, 0x3a, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x5f, 0x4f, 0x6d, 0x6e, 0x69, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x4f, 0x6d, 0x6e,
	0x69, 0x5f, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x4f, 0x6d, 0x6e, 0x69, 0x22, 0x00, 0x30, 0x01, 0x32, 0x40,
	0x0a, 0x0b, 0x59, 0x6f, 0x6c, 0x6f, 0x5f, 0x4b, 0x69, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x31, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x5f, 0x4b, 0x69, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x4b, 0x69, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x00,
	0x32, 0x43, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x61, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x32, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x42, 0x53, 0x12,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x42, 0x53, 0x1a,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x74, 0x6f,
	0x5f, 0x42, 0x53, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x64, 0x61, 0x6e, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x70, 0x79,
	0x74, 0x68, 0x6f, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_message_proto_goTypes = []interface{}{
	(*Object_Kinect)(nil),      // 0: pb.Object_Kinect
	(*Object_Omni)(nil),        // 1: pb.Object_Omni
	(*Request_Omni_Calib)(nil), // 2: pb.Request_Omni_Calib
	(*Request)(nil),            // 3: pb.Request
	(*Request_BS)(nil),         // 4: pb.Request_BS
	(*Response_Omni)(nil),      // 5: pb.Response_Omni
	(*Response_Kinect)(nil),    // 6: pb.Response_Kinect
	(*ResponseTo_BS)(nil),      // 7: pb.Response_to_BS
}
var file_message_proto_depIdxs = []int32{
	1, // 0: pb.Response_Omni.objects:type_name -> pb.Object_Omni
	0, // 1: pb.Response_Kinect.objects:type_name -> pb.Object_Kinect
	2, // 2: pb.Yolo_Omni.Send_Omni:input_type -> pb.Request_Omni_Calib
	3, // 3: pb.Yolo_Kinect.Send_Kinect:input_type -> pb.Request
	4, // 4: pb.Base_Satation.Send_to_BS:input_type -> pb.Request_BS
	5, // 5: pb.Yolo_Omni.Send_Omni:output_type -> pb.Response_Omni
	6, // 6: pb.Yolo_Kinect.Send_Kinect:output_type -> pb.Response_Kinect
	7, // 7: pb.Base_Satation.Send_to_BS:output_type -> pb.Response_to_BS
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object_Kinect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object_Omni); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_Omni_Calib); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_BS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Omni); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Kinect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseTo_BS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
